spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/gzz02
    username: root
    password: root
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: 10.10.58.238
    port: 6379
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8088
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  format_sql: true